
[window]
padding.x = 10
padding.y = 10
decorations = "buttonless"

[font]
size = 10

normal = { family = "MesloLGS Nerd Font Mono", style = "Regular" }
bold = { family = "MesloLGS Nerd Font Mono", style = "Bold" }
italic = { family = "MesloLGS Nerd Font Mono", style = "Italic" }

[general]
import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]
